Updated workflow

diff --git a/.github/workflows/infisical.yml b/.github/workflows/infisical.yml
--- a/.github/workflows/infisical.yml
+++ b/.github/workflows/infisical.yml
@@ -12,7 +12,8 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v4
+    - name: Checkout
+      uses: actions/checkout@v4
     - name: Infisical Login
       uses: Infisical/secrets-action@v1.0.9
       with:
@@ -23,5 +24,5 @@ jobs:
         client-secret: "${{ secrets.INFISICAL_CLIENT_SECRET }}"
     - name: Debug Output
       run: |
-        echo "Fastmail SMTP Host: $FASTMAIL_SMTP_HOST"
-      
+        [ ! "${GITHUB_ACTION_DUMMY}" == "DUMMY" ] && echo "Secret Test Failed" && exit 1
+        echo "Secret Test Passed"
